### ISSUE TITLE
Inconsistencies with Fee and Traded values on certain transactions

### ISSUE THREAD

**Issue by MitchellCash** [ligerzero459/PaycoinBlockExplorer#7]
Fee and Traded values seem to be swapped or misrepresented on Newly Generated Coins Transactions and Coinstake Transactions from on the left panel compared to the right panel.

Example of Newly Generated Coins `(inconsistent)`:
http://testnet.paycoinexplorer.info/tx/a245c6da255ff77735d6c6d84a808398a16850b56ebf911fcd5dfdf6af3e8112
![](https://dl.dropboxusercontent.com/u/37902134/GitHub/ligerzero459%3APaycoinBlockExplorer/%237_0.png)

Example of Coinstake Transaction `(inconsistent)`:
http://testnet.paycoinexplorer.info/tx/614f789f8d355d2b329d49fb911f4c9302dac4ff0587ef2bc20b6dcc794de177
![](https://dl.dropboxusercontent.com/u/37902134/GitHub/ligerzero459%3APaycoinBlockExplorer/%237_1.png)

Example of Simple Transaction with Input `(seems okay)`:
http://testnet.paycoinexplorer.info/tx/f94445d3e6415c9e046924edc77883e76208574df2cdff0fd1cf1f3a3fa46df4
![](https://dl.dropboxusercontent.com/u/37902134/GitHub/ligerzero459%3APaycoinBlockExplorer/%237_2.png)

**Comment by ligerzero459** [comment]
Misrepresented is probably the best way to put that. I'll work up a change that renames fee in the left box to "generated" or "created" or something like that on proof of work or proof of stake transactions.

**Comment by MitchellCash** [comment]
Awesome stuff! By the way, what is Traded?

**Comment by ligerzero459** [comment]
It depends on the transaction type. On normal transactions, it's the total coins output. On PoW and PoS transactions, it's the amount created/generated. Or it will be once I merge this update

**Comment by ligerzero459** [comment]
Okay, should be fixed in [`346262145299a181a41220a8dd6bf01f13a5f185`](https://github.com/ligerzero459/PaycoinBlockExplorer/commit/346262145299a181a41220a8dd6bf01f13a5f185)

**Comment by MitchellCash** [comment]
Looks good to me! Thanks.
