### ISSUE TITLE
Change block page URL from hash to height

### ISSUE THREAD

**Issue by MitchellCash** [ligerzero459/PaycoinBlockExplorer#9]
Whereas a transaction is more commonly known by its hash I think a block is more commonly known by its height rather than the hash.

It also allows easier manipulation in the URL bar when searching for a block - you can just change the block height at the end of the URL to directly load the page.

**Comment by ligerzero459** [comment]
Sure, this can be done. I actually changed it from height to hash during creation since everyone's used to ledger. Personally, I like heights too, so I'll change it back :+1:

**Comment by MitchellCash** [comment]
Oh right. I actually don't mind which way it goes I was thinking of the usefulness of the URL bar but I guess there could be arguments either way. 

Looking at blockchain.info they actually use hash. I don't mind which one actually :) haha

**Comment by MitchellCash** [comment]
Actually blockchain does both...

https://blockchain.info/block-index/1074991
and
https://blockchain.info/block/000000000000000003a3f6d2d65755809a782b63edacf2cc3392b11a82b85095

maybe that's possible

**Comment by ligerzero459** [comment]
Hmmm, they use a separate route to do it. That's super easy. I'll do that in the morning
